### ISSUE TITLE
support Chinese

### ISSUE THREAD

**Issue by Huijies** [VR2TE/Talkpod-A36plus-Firmware#1]
The official version 2.0 has been released, can you modify it to support the full band and support Chinese? Thank you very much!

**Comment by VR2TE** [comment]
I am glad to receive attention and I will work hard to release the Chinese version as soon as possible.

**Comment by VR2TE** [comment]
The CN version has been uploaded, I will continue to pay attention to the official firmware, and explore more interesting features.

**Comment by Huijies** [comment]
> 
Thank you very much for your outstanding work! If it is convenient, if you can teach the relevant technology, it is even better!

**Comment by LeePeiee** [comment]
Very thank
