### ISSUE TITLE
Update OpenRTX KDHX file available in this repository

### ISSUE THREAD

**Issue by Tunas1337** [VR2TE/Talkpod-A36plus-Firmware#6]
Hello, I've made some big changes to the OpenRTX port, including (finally!) full power TX. So far it's only for VHF, but we'll figure it out. It also has proper VHF/UHF RX now. If you'd like, please update the KDHX file available. If you cannot compile it for some reason, I will happily help.

**Comment by VR2TE** [comment]
I am very happy to see this news, I add you as the project partner, and we will maintain this project together

**Comment by VR2TE** [comment]
Technically, it's not a project, it's just a collection site, because I can't find the right place

**Comment by Tunas1337** [comment]
Thank you, closing this issue because I will update the file through a commit.
